spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: ***REMOVED_DB_PASSWORD***

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.intelijake.mall.pojo
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8080

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:***REMOVED_AWS_ACCESS_KEY***}
      secretKey: ${AWS_SECRET_ACCESS_KEY:***REMOVED_AWS_SECRET_KEY***}
    region: ${AWS_REGION:eu-west-1}
    s3:
      bucket: ${AWS_S3_BUCKET:jake-mall-bucket}


